# In "1.4.1 Faster Linking" of Zero To Production In Rust linking
# speed is discussed; now using mold per
# https://stackoverflow.com/a/70378019 /
# https://github.com/rui314/mold?tab=readme-ov-file#how-to-use
#
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/bin/mold"]
